import type { KanbanCard, TimelineEvent } from "./types";

const nowIso = (offsetMin = 0) =>
  new Date(Date.now() - offsetMin * 60_000).toISOString();


export const seedTimeline: TimelineEvent[] = [
  {
    id: "evt_1",
    ts: nowIso(0.1),
    agentId: "agt_atlas",
    agentName: "Atlas",
    level: "tool",
    category: "tool",
    title: "Grep('useReducer', src/**)",
    detail: "127 matches across 41 files",
  },
  {
    id: "evt_2",
    ts: nowIso(0.6),
    agentId: "agt_orion",
    agentName: "Orion",
    level: "success",
    category: "agent",
    title: "Tests passed",
    detail: "vitest · 312 passed · 0 failed · 1.4s",
  },
  {
    id: "evt_3",
    ts: nowIso(1.4),
    agentId: "agt_atlas",
    agentName: "Atlas",
    level: "info",
    category: "chat",
    title: "Assistant turn (412 tokens)",
  },
  {
    id: "evt_4",
    ts: nowIso(2.1),
    agentId: "agt_rigel",
    agentName: "Rigel",
    level: "error",
    category: "agent",
    title: "Connection refused: pg://prod-01",
    detail: "Retrying in 8s (3/5)",
  },
  {
    id: "evt_5",
    ts: nowIso(3),
    agentId: "agt_vega",
    agentName: "Vega",
    level: "warn",
    category: "tool",
    title: "Edit blocked by hook",
    detail: "format-on-save reverted 1 file",
  },
  {
    id: "evt_6",
    ts: nowIso(5),
    agentId: "agt_nova",
    agentName: "Nova",
    level: "success",
    category: "agent",
    title: "Migration 0042 applied",
    detail: "users +1 column · backfilled 50M rows",
  },
  {
    id: "evt_7",
    ts: nowIso(8),
    level: "info",
    category: "system",
    title: "Bridge → claude CLI v2.1.89",
  },
];

export const seedKanban: KanbanCard[] = [
  {
    id: "k1",
    title: "Audit auth flows for SSRF",
    agentId: "agt_vega",
    agentName: "Vega",
    priority: "high",
    column: "backlog",
    createdAt: nowIso(120),
  },
  {
    id: "k2",
    title: "Refactor billing/charges.ts",
    agentId: "agt_atlas",
    agentName: "Atlas",
    priority: "medium",
    column: "backlog",
    createdAt: nowIso(90),
  },
  {
    id: "k3",
    title: "Write tests for invoices module",
    agentId: "agt_orion",
    agentName: "Orion",
    priority: "high",
    column: "running",
    createdAt: nowIso(40),
  },
  {
    id: "k4",
    title: "Map monorepo dependencies",
    agentId: "agt_atlas",
    agentName: "Atlas",
    priority: "medium",
    column: "running",
    createdAt: nowIso(60),
  },
  {
    id: "k5",
    title: "Draft release notes v3.4",
    agentId: "agt_lyra",
    agentName: "Lyra",
    priority: "low",
    column: "review",
    createdAt: nowIso(220),
  },
  {
    id: "k6",
    title: "Migrate users table → uuid",
    agentId: "agt_nova",
    agentName: "Nova",
    priority: "high",
    column: "done",
    createdAt: nowIso(720),
  },
  {
    id: "k7",
    title: "Bump deps & rebuild lockfile",
    priority: "low",
    column: "done",
    createdAt: nowIso(1440),
  },
];
